export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const CLEAR_ERRORS = 'CLEAR_ERRORS'



export const REGISTER_REQUEST='REGISTER_REQUEST'
export const REGISTER_SUCCESS='REGISTER_SUCCESS'
export const REGISTER_FAIL='REGISTER_FAIL'

export const FORGOT_REQUEST='FORGOT_REQUEST'
export const FORGOT_SUCCESS='FORGOT_SUCCESS'
export const FORGOT_FAIL='FORGOT_FAIL'


    export const LOAD_USERS='LOAD_USERS'
    export const LOAD_SUCCESS='LOAD_SUCCESS'
    export const LOAD_FAILURE='LOAD_FAILURE'


    export const LOGOUT_SUCCESS='LOGOUT_SUCCESS'
    export const LOGOUT_FAILURE='LOGOUT_FAILURE'


    export const UPDATE_PASSWORD_SUCCESS='UPDATE_PASSWORD_SUCCESS'
    export const UPDATE_PASSWORD_LOAD='UPDATE_PASSWORD_LOAD'
    export const UPDATE_PASSWORD_FAILURE='UPDATE_PASSWORD_FAILURE'
    
